# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e981993ed3e85c8c88b2846966ed0655bd1ce6a71762d2df14a30de583a412d10e358fd900444c3b54fd3b705587d598b2af7ad79c29ac913961689902e563ca

test:
  secret_key_base: ad6f1b47225c50a2b4d44c3d5f588176e19530bc48f006eaef226576a3fc9448d70dabe6862160770d0dd6ea0d0b070d7e4218a3edba9b81b4c2c206a3e74164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
